#%RAML 0.8
title: unvr-esb-pa-salesorder-app-dev01
version: 1.0
baseUri: http://unvr-esb-pa-salesorder-app-dev01.cloudhub.io/
mediaType: application/xml
protocols: [HTTP,HTTPS]
/sales-order:
  displayName: Process sales order
  post:
    description: Process sales order
    body: 
      application/xml:
        example: | 
          <?xml version="1.0" encoding="utf-8"?>
          <CumulativeTotalRequest xmlns="http://com.univar/data/enterprise/business/salesorder/messages/1.0">
            <CorpCode>01</CorpCode>
            <CustAROfficeCode>01</CustAROfficeCode>
            <CustomerNumber>116368</CustomerNumber>
            <CustomerShipToSuffix>001</CustomerShipToSuffix>
            <OrderEntryStartDate>2015-01-01</OrderEntryStartDate>
            <OrderEntryEndDate>2015-12-03</OrderEntryEndDate>
          </CumulativeTotalRequest>
    responses: 
      200: 
        body: 
          application/xml:
            example: | 
              <?xml version="1.0" encoding="utf-8"?>
              <CumulativeTotalResponse xmlns="http://com.univar/data/enterprise/business/salesorder/messages/1.0">
                <Total>123.45</Total>
              </CumulativeTotalResponse>

/invoice-details:
  displayName: Get OSG invoice PDF URL
  post:
    description: Get OSG invoice PDF URL
    body: 
      application/xml:
        example: | 
          <?xml version="1.0" encoding="UTF-8"?>
            <invoiceReqRes:InvoiceRequest xmlns="urn:cidx:names:specification:ces:schema:all:5:3" xmlns:ex="http://com.univar/data/enterprise/core/exception/1.0" xmlns:invoiceReqRes="http://com.univar/data/enterprise/business/invoice/message/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
              <invoiceReqRes:ResultSet>
                <invoiceReqRes:row>
                  <invoiceReqRes:Invoice_Number>
                    <DocumentReference>
                      <DocumentIdentifier>a</DocumentIdentifier>
                    </DocumentReference>
                  </invoiceReqRes:Invoice_Number>
                  <invoiceReqRes:Sales_Office_ID>String</invoiceReqRes:Sales_Office_ID>
                  </invoiceReqRes:row>
              </invoiceReqRes:ResultSet>
            </invoiceReqRes:InvoiceResponse>
    responses: 
      200: 
        body: 
          application/xml:
            example: | 
               <?xml version="1.0" encoding="UTF-8"?>
                <invoiceReqRes:InvoiceResponse xmlns="urn:cidx:names:specification:ces:schema:all:5:3" xmlns:ex="http://com.univar/data/enterprise/core/exception/1.0" xmlns:invoiceReqRes="http://com.univar/data/enterprise/business/invoice/message/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                  <invoiceReqRes:ResultSet>
                    <invoiceReqRes:row>
                    <invoiceReqRes:OSGUrl>String</invoiceReqRes:OSGUrl>
                  </invoiceReqRes:row>
                 </invoiceReqRes:ResultSet>
                </invoiceReqRes:InvoiceResponse>
  /{invoiceNumber}:
    get:
      description: Get OSG invoice PDF URL by invoice number
      queryParameters: 
        salesoffice: 
          description: Sales office  
      responses: 
        200: 
          body: 
            text/plain:                
/cases-orderhistory:

   displayName: Query using Customer Purchase Order Number, Ship to Number and Shipped date range
   post:
    description: Query using Customer Purchase Order Number, Ship to Number and Shipped date range received from Salesforce
    body:
      application/xml:
        example: |
          <CaseSearchRequest>
            <Lot_Number></Lot_Number>
            <ShipTo_Number>161267</ShipTo_Number>
            <Shipped_Date_Range>20150102</Shipped_Date_Range>
            <Invoice_Number>26910</Invoice_Number>
            <Sales_Office_Code>CL</Sales_Office_Code>
            <Product_Number>192220</Product_Number>
            <ShipTo_Number>160053</ShipTo_Number>
            <Shipped_Date_Range>20150729</Shipped_Date_Range>
            <Sales_Order_Number>760501</Sales_Order_Number>
            <Sales_Office_Code>IN</Sales_Office_Code>
            <Customer_PO>MU637359</Customer_PO>
            <ShipTo_Number>697908</ShipTo_Number>
            <Shipped_Date_Range>20150102</Shipped_Date_Range>
          </CaseSearchRequest
    responses:  
      200:
        body:
          application/xml:
            example: |
                    <response>
                      <record>
                      <Customer_Ship_To_Number>261718</Customer_Ship_To_Number>
                      <Customer_Ship_To_Name>191990</Customer_Ship_To_Name>
                      <Sales_Order_Number>892195</Sales_Order_Number>
                      <Invoice_Number_Sales_Office>119564PX</Invoice_Number_Sales_Office>
                      <Customer_PO_Number>57127</Customer_PO_Number>
                      <Order_Ship_Date>20110201</Order_Ship_Date>
                      </record>
                    </response>
/orderhistory:
  /status:
   displayName: Query using Customer Purchase Order Number, Ship to Number and Shipped date range
   post:
    description: Query using Customer Purchase Order Number, Ship to Number and Shipped date range received from Salesforce
    body:
      application/xml:
        example: |
          <?xml version="1.0" encoding="UTF-8"?>
          <orderRes:OrderRequest xmlns="urn:cidx:names:specification:ces:schema:all:5:3" xmlns:types="http://com.univar/data/enterprise/core/types/1.1" xmlns:order="http://com.univar/data/enterprise/business/order/1.1" xmlns:orderRes="http://com.univar/data/enterprise/business/order/message/1.1">
              <order:Order_Date>
                           <types:FromDate>2015-06-07</types:FromDate>
                           <types:ToDate>2016-06-07</types:ToDate>
              </order:Order_Date>
              <order:Status>ALL</order:Status>
              <order:Account>
                           <order:Corp_acct_id Agency="AGIIS-EBID">4422</order:Corp_acct_id>
              </order:Account>
            </orderRes:OrderRequest>
          
    responses:  
      200:
        body:
          application/xml:
            example: |
                    <?xml version="1.0" encoding='windows-1252'?>
                      <orderRes:OrderResponse xmlns:orderRes="http://com.univar/data/enterprise/business/order/message/1.0">
                      <orderRes:ResultSet>
                        <orderRes:row xmlns:orderRes="http://com.univar/data/enterprise/business/order/message/1.0">
                        <orderRes:Account_Manager/>
                        <orderRes:Customer_PO_Number>
                          <DocumentIdentifier>R45388</DocumentIdentifier>
                        </orderRes:Customer_PO_Number>
                        <orderRes:Account_PO_Number>
                          <DocumentIdentifier/>
                        </orderRes:Account_PO_Number>
                        <orderRes:Univar_PO_Number>
                          <DocumentIdentifier/>
                        </orderRes:Univar_PO_Number>
                        <orderRes:Product_Name/>
                        <orderRes:Lot_Number BatchNumberCreator="Manufacturer"/>
                        <orderRes:Order_Ship_Date>2016-02-05</orderRes:Order_Ship_Date>
                        <orderRes:Invoice_Number>
                          <DocumentReference>
                            <DocumentIdentifier>280853</DocumentIdentifier>
                          </DocumentReference>
                        </orderRes:Invoice_Number>
                        <orderRes:Sales_Office_ID>KT</orderRes:Sales_Office_ID>
                        <orderRes:Sales_Order_Number>
                          <DocumentReference>
                            <DocumentIdentifier>55342</DocumentIdentifier>
                          </DocumentReference>
                        </orderRes:Sales_Order_Number>
                        <orderRes:Ship_from_Warehouse>
                          <PartnerInformation>
                            <PartnerName/>
                            <PartnerIdentifier Agency="AGIIS-EBID"/>
                          </PartnerInformation>
                        </orderRes:Ship_from_Warehouse>
                        <orderRes:Requesting_Warehouse>
                        <RequestedDocumentTypeCode Domain="UN/EDIFACT 1001"/>
                        <DocumentRecipientInformation DeliveryMethodQualifier="Email">
                        <DocumentRecipientPartner PartnerRole="AdditionalCarrier">
                        <PartnerInformation>
                          <PartnerName/>
                          <PartnerIdentifier Agency="AGIIS-EBID"/>
                        </PartnerInformation>
                        </DocumentRecipientPartner>
                        <DocumentDeliveryMethod/>
                        <LanguageCode Domain="ISO-639-2T"/>
                        <NumberOfOriginals/>
                        <NumberOfCopies/>
                        </DocumentRecipientInformation>
                        </orderRes:Requesting_Warehouse>
                        <orderRes:Shipping_Type/>
                        <orderRes:Shipping_Term Domain="ANSI-ASC-X12-146"/>
                        <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                        <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                        <orderRes:Vendor_Name/>
                        <orderRes:Quantity_Shipped_Customer>
                          <Measurement>
                            <MeasurementValue/>
                            <UnitOfMeasureCode Domain="UN-Rec-20"/>
                          </Measurement>
                        </orderRes:Quantity_Shipped_Customer>
                        <orderRes:Shipping_Method/>
                        <orderRes:Vendor_Shipment_Method/>
                        <orderRes:Quantity_Shipped_From_Vendor>
                          <Measurement>
                            <MeasurementValue/>
                            <UnitOfMeasureCode Domain="UN-Rec-20"/>
                          </Measurement>
                        </orderRes:Quantity_Shipped_From_Vendor>
                        <orderRes:Product_Number Agency="AGIIS-ProductID"/>
                        <orderRes:Order_Date>2015-12-08</orderRes:Order_Date>
                        <orderRes:Status>CLOSED</orderRes:Status>
                        <orderRes:Ship_to_name>
                        <PartnerInformation>
                          <PartnerName/>
                          <PartnerIdentifier Agency="AGIIS-EBID"/>
                          <AddressInformation>
                            <AddressLine/>
                            <CityName/>
                            <StateOrProvince/>
                            <PostalCode/>
                            <PostalCountry/>
                            <LocationCode Domain="AGIIS-EBID"/>
                            </AddressInformation>
                            </PartnerInformation>
                            </orderRes:Ship_to_name>
                            <orderRes:ESTIMATED_SHIP_DATE>
                            <DateTime DateTimeQualifier="After"/>
                            </orderRes:ESTIMATED_SHIP_DATE>
                            <orderRes:ESTIMATED_DELIVERY_DATE/>
                            <orderRes:FOB/>
                            <orderRes:SHIP_VIA>
                              <PartnerInformation>
                                <PartnerName/>
                                <PartnerIdentifier Agency="AGIIS-EBID"/>
                              <AddressInformation>
                               <AddressLine/>
                               <CityName/>
                               <StateOrProvince/>
                               <PostalCode/>
                               <PostalCountry/>
                               <LocationCode Domain="ISO-3166-1"/>
                              </AddressInformation>
                              </PartnerInformation>
                             </orderRes:SHIP_VIA>
                             <orderRes:CURRENCY Domain="ISO-4217"/>
                             <orderRes:QTY>
                              <Measurement>
                              <MeasurementValue/>
                              <UnitOfMeasureCode Domain="UN-Rec-20"/>
                              </Measurement>
                            </orderRes:QTY>
                            <orderRes:BO>
                            <Measurement>
                              <MeasurementValue/>
                              <UnitOfMeasureCode Domain="UN-Rec-20"/>
                            </Measurement>
                            </orderRes:BO>
                            <orderRes:Size>
                            <Measurement>
                              <MeasurementValue/>
                              <UnitOfMeasureCode Domain="UN-Rec-20"/>
                            </Measurement>
                            </orderRes:Size>
                            <orderRes:item_number/>
                            <orderRes:Product_Description/>
                            <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="a">
                            <MonetaryAmount>
                              <MonetaryValue/>
                              <CurrencyCode Domain="ISO-4217"/>
                            </MonetaryAmount>
                            </orderRes:Unit_Price>
                            <orderRes:Line_total>
                              <MonetaryAmount>
                                <MonetaryValue/>
                                <CurrencyCode Domain="ISO-4217"/>
                              </MonetaryAmount>
                            </orderRes:Line_total>
                            <orderRes:Last_Modified_Date>2016-02-29</orderRes:Last_Modified_Date>
                            <orderRes:Account>
                              <orderRes:Ship_To Agency="AGIIS-EBID"/>
                              <orderRes:Bill_To Agency="AGIIS-EBID"/>
                              <orderRes:Corp_acct_id Agency="AGIIS-EBID"/>
                            </orderRes:Account>
                          </orderRes:row>  
                         </orderRes:ResultSet>
                        </orderRes:OrderResponse>
   /2.0:  
     displayName: Query using Customer Sales Order Number, Ship to Number and Shipped date range
     post:
      description: Query using Customer Purchase Order Number, Ship to Number and Shipped date range received from Salesforce
      body:
        application/xml:
         example: |
          <?xml version="1.0" encoding="UTF-8"?>
          <orderRes:OrderRequest xmlns:order="http://com.univar/data/enterprise/business/order/1.2" xmlns:orderRes="http://com.univar/data/enterprise/business/order/message/1.3" xmlns:typ="http://com.univar/data/enterprise/core/types/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <order:Customer_PO_Number>
              <DocumentIdentifier>FT_20245</DocumentIdentifier>
            </order:Customer_PO_Number>
            <order:Product_Name/>
            <order:Lot_Number BatchNumberCreator="Manufacturer"/>
            <order:Order_Ship_Date>
              <typ:FromDate>1967-08-13</typ:FromDate>
              <typ:ToDate>1967-08-13</typ:ToDate>
            </order:Order_Ship_Date>
            <order:Invoice_Number>
              <DocumentReference>
                <DocumentIdentifier>629533</DocumentIdentifier>
              </DocumentReference>
            </order:Invoice_Number>
            <order:Sales_Order_Number>
              <DocumentReference>
                <DocumentIdentifier>370415</DocumentIdentifier>
              </DocumentReference>
            </order:Sales_Order_Number>
            <order:Sales_Office_ID>AT</order:Sales_Office_ID>
            <order:Product_Number Agency="AGIIS-ProductID"/>
            <order:Product_Customer_code Agency="AGIIS-ProductID"/>
            <order:Univar_Product_code Agency="AGIIS-ProductID"/>
            <order:Order_Date>
              <typ:FromDate>2016-08-01</typ:FromDate>
              <typ:ToDate>2017-02-15</typ:ToDate>
            </order:Order_Date>
            <order:Invoice_Date>
              <typ:FromDate>1957-08-13</typ:FromDate>
              <typ:ToDate>1957-08-13</typ:ToDate>
            </order:Invoice_Date>
            <order:Order_Status>ALL</order:Order_Status>
            <order:Invoice_Status>ALL</order:Invoice_Status>
            <order:Source>USA_DCS</order:Source>
            <order:Account>
            <order:Ship_To>
              <PartnerInformation>
                <PartnerName/>
                <PartnerIdentifier>002</PartnerIdentifier>
                <AddressInformation>
                  <AddressLine/>
                  <CityName/>
                  <StateOrProvince/>
                  <PostalCode/>
                  <PostalCountry/>
                  <LocationCode/>
                </AddressInformation>
              </PartnerInformation>
            </order:Ship_To>
            <order:Bill_To>
              <PartnerInformation>
                <PartnerName/>
                <PartnerIdentifier>615659</PartnerIdentifier>
                <AddressInformation>
                  <AddressLine/>
                  <CityName/>
                  <StateOrProvince/>
                  <PostalCode/>
                  <PostalCountry/>
                  <LocationCode/>
                </AddressInformation>
              </PartnerInformation>
            </order:Bill_To>
            <order:Corp_acct_id Agency="AGIIS-EBID">4422</order:Corp_acct_id>
            </order:Account>
          </orderRes:OrderRequest>

      responses:  
        200:
          body:
            application/xml:
             example: |
                 <?xml version="1.0" encoding='windows-1252'?>
                      <orderRes:OrderResponse xmlns:orderRes="http://com.univar/data/enterprise/business/order/message/1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                      <orderRes:ResultSet>
                        <orderRes:row>
                            <orderRes:Account_Manager/>
                            <orderRes:Customer_PO_Number>
                              <DocumentIdentifier>7400166276 REL:4367</DocumentIdentifier>
                            </orderRes:Customer_PO_Number>
                            <orderRes:Account_PO_Number/>
                            <orderRes:Univar_PO_Number/>
                            <orderRes:Order_Ship_Date>2016-11-02</orderRes:Order_Ship_Date>
                            <orderRes:Last_Modified_Date>2017-01-31</orderRes:Last_Modified_Date>
                            <orderRes:Sales_Office_ID>SP</orderRes:Sales_Office_ID>
                            <orderRes:Sales_Order_Number>
                              <DocumentReference>
                                <DocumentIdentifier>914998</DocumentIdentifier>
                              </DocumentReference>
                            </orderRes:Sales_Order_Number>
                            <orderRes:Order_Date>2016-10-27T00:00:00</orderRes:Order_Date>
                            <orderRes:CSR_Name>LEIGH HEDRICK</orderRes:CSR_Name>
                            <orderRes:CSR_Email>IELYD@UNIVARUSA.COM</orderRes:CSR_Email>
                            <orderRes:CSR_Phone></orderRes:CSR_Phone>
                            <orderRes:Status>L</orderRes:Status>
                            <orderRes:CURRENCY Domain="ISO-4217">USD</orderRes:CURRENCY>
                            <orderRes:Account>
                              <orderRes:Ship_To>
                                <PartnerInformation>
                                  <PartnerName>ROCHE CAROLINA INC</PartnerName>
                                  <PartnerIdentifier>001</PartnerIdentifier>
                                  <AddressInformation>
                                    <AddressLine>MANUFACTURING CHEMICALS</AddressLine>
                                    <CityName>FLORENCE</CityName>
                                    <StateOrProvince>SC</StateOrProvince>
                                    <PostalCode>29506</PostalCode>
                                    <PostalCountry></PostalCountry>
                                    <LocationCode></LocationCode>
                                  </AddressInformation>
                               </PartnerInformation>
                             </orderRes:Ship_To>
                             <orderRes:Bill_To>
                               <PartnerInformation>
                                  <PartnerName></PartnerName>
                                  <PartnerIdentifier>350428</PartnerIdentifier>
                                  <AddressInformation>
                                     <AddressLine>MANUFACTURING CHEMICALS</AddressLine>
                                    <CityName>FLORENCE</CityName>
                                    <StateOrProvince>SC</StateOrProvince>
                                    <PostalCode>29506</PostalCode>
                                    <PostalCountry></PostalCountry>
                                    <LocationCode></LocationCode>
                                  </AddressInformation>
                                </PartnerInformation>
                              </orderRes:Bill_To>
                              <orderRes:Corp_acct_id>0</orderRes:Corp_acct_id>
                            </orderRes:Account>
                            <orderRes:Invoice_Details>
                              <InvoiceNumber>
                                <DocumentReference>
                                <DocumentIdentifier>177581</DocumentIdentifier>
                                </DocumentReference>
                              </InvoiceNumber>
                              <InvoiceType/>
                              <InvoiceDate>
                                <DateTime DateTimeQualifier="After">2016-11-01T00:00:00</DateTime>
                              </InvoiceDate>
                              <InvoiceTotals>
                                <TotalLineItems>1</TotalLineItems>
                                <InvoiceTotal>
                                  <MonetaryAmount>
                                    <MonetaryValue>30270.3800</MonetaryValue>
                                    <CurrencyCode>USD</CurrencyCode>
                                  </MonetaryAmount>
                                </InvoiceTotal>
                              </InvoiceTotals>
                            </orderRes:Invoice_Details>
                            <orderRes:Line_Items>
                              <orderRes:QTY>
                                <Measurement>
                                  <MeasurementValue>45000.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">PO</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:QTY>
                              <orderRes:BO>
                               <Measurement>
                                  <MeasurementValue>45000.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">PO</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:BO>
                              <orderRes:Size>
                                <Measurement>
                                  <MeasurementValue>1.0000</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">LB</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:Size>
                              <orderRes:item_number>605649</orderRes:item_number>
                              <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="KG">
                                <MonetaryAmount>
                                  <MonetaryValue>1.4950</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Unit_Price>
                              <orderRes:Line_total>
                                <MonetaryAmount>
                                  <MonetaryValue>30270.3800</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Line_total>
                              <orderRes:Product_Number Agency="AGIIS-ProductID">605649</orderRes:Product_Number>
                              <orderRes:Product_Description>METHYLENE CHLORIDE</orderRes:Product_Description>
                              <orderRes:SdsNumber>OC79584</orderRes:SdsNumber>
                              <orderRes:Lot_Number BatchNumberCreator="Manufacturer">SP619816</orderRes:Lot_Number>
                              <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                              <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                              <orderRes:Vendor_Name>honeywell</orderRes:Vendor_Name>
                           </orderRes:Line_Items>
                            <orderRes:Line_Items>
                              <orderRes:QTY>
                                <Measurement>
                                  <MeasurementValue>1.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:QTY>
                              <orderRes:BO>
                                <Measurement>
                                  <MeasurementValue>0.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:BO>
                              <orderRes:Size>
                                <Measurement>
                                  <MeasurementValue>1.0000</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:Size>
                              <orderRes:item_number>644037</orderRes:item_number>
                              <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="EA">
                                <MonetaryAmount>
                                  <MonetaryValue>0.0000</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Unit_Price>
                              <orderRes:Line_total>
                                <MonetaryAmount>
                                  <MonetaryValue>0.0000</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Line_total>
                              <orderRes:Product_Number Agency="AGIIS-ProductID">644037</orderRes:Product_Number>
                              <orderRes:Product_Description>UNV BULK DLVY CHG</orderRes:Product_Description>
                              <orderRes:Lot_Number BatchNumberCreator="Manufacturer"/>
                              <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                              <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                              <orderRes:Vendor_Name/>
                           </orderRes:Line_Items>
                           <orderRes:Line_Items>
                              <orderRes:QTY>
                                <Measurement>
                                  <MeasurementValue>1.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:QTY>
                              <orderRes:BO>
                                <Measurement>
                                  <MeasurementValue></MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20"></UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:BO>
                              <orderRes:Size>
                                <Measurement>
                                  <MeasurementValue>1.0000</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:Size>
                              <orderRes:item_number>777722</orderRes:item_number>
                              <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="EA">
                                <MonetaryAmount>
                                  <MonetaryValue>0.0000</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Unit_Price>
                              <orderRes:Line_total>
                                <MonetaryAmount>
                                  <MonetaryValue>0.0000</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Line_total>
                              <orderRes:Product_Number Agency="AGIIS-ProductID">777722</orderRes:Product_Number>
                              <orderRes:Product_Description>TRANSPORTATION SURCHG</orderRes:Product_Description>
                              <orderRes:Lot_Number BatchNumberCreator="Manufacturer"/>
                              <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                              <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                              <orderRes:Vendor_Name/>
                           </orderRes:Line_Items>
                        </orderRes:row> 
                        <orderRes:row>
                            <orderRes:Account_Manager/>
                            <orderRes:Customer_PO_Number>
                              <DocumentIdentifier>225009147 ITEM# 22113109</DocumentIdentifier>
                            </orderRes:Customer_PO_Number>
                            <orderRes:Account_PO_Number/>
                            <orderRes:Univar_PO_Number/>
                            <orderRes:Order_Ship_Date>2017-01-19</orderRes:Order_Ship_Date>
                            <orderRes:Last_Modified_Date>2017-01-20T00:00:00</orderRes:Last_Modified_Date>
                            <orderRes:Sales_Office_ID>LA</orderRes:Sales_Office_ID>
                            <orderRes:Sales_Order_Number>
                              <DocumentReference>
                                <DocumentIdentifier>889352</DocumentIdentifier>
                              </DocumentReference>
                            </orderRes:Sales_Order_Number>
                            <orderRes:Order_Date>2017-01-13</orderRes:Order_Date>
                            <orderRes:CSR_Name>CELY RAMOS</orderRes:CSR_Name>
                            <orderRes:CSR_Email>IECAR@UNIVARUSA.COM</orderRes:CSR_Email>
                            <orderRes:CSR_Phone></orderRes:CSR_Phone>
                            <orderRes:Status>L</orderRes:Status>
                            <orderRes:CURRENCY Domain="ISO-4217">USD</orderRes:CURRENCY>
                            <orderRes:Account>
                              <orderRes:Ship_To>
                                <PartnerInformation>
                                  <PartnerName>CYTEC ENGINEERED MATLS</PartnerName>
                                  <PartnerIdentifier>002</PartnerIdentifier>
                                  <AddressInformation>
                                    <AddressLine>645 CYPRESS ST</AddressLine>
                                    <CityName>ORANGE</CityName>
                                    <StateOrProvince>CA</StateOrProvince>
                                    <PostalCode>92867</PostalCode>
                                    <PostalCountry></PostalCountry>
                                    <LocationCode></LocationCode>
                                  </AddressInformation>
                               </PartnerInformation>
                             </orderRes:Ship_To>
                             <orderRes:Bill_To>
                               <PartnerInformation>
                                  <PartnerName></PartnerName>
                                  <PartnerIdentifier>305963</PartnerIdentifier>
                                  <AddressInformation>
                                    <AddressLine>645 CYPRESS ST</AddressLine>
                                    <CityName>ORANGE</CityName>
                                    <StateOrProvince>CA</StateOrProvince>
                                    <PostalCode>92867</PostalCode>
                                    <PostalCountry></PostalCountry>
                                    <LocationCode></LocationCode>
                                  </AddressInformation>
                                </PartnerInformation>
                              </orderRes:Bill_To>
                              <orderRes:Corp_acct_id>8031</orderRes:Corp_acct_id>
                            </orderRes:Account>
                            <orderRes:Invoice_Details>
                              <InvoiceNumber>
                                <DocumentReference>
                                <DocumentIdentifier>165666</DocumentIdentifier>
                                </DocumentReference>
                              </InvoiceNumber>
                              <InvoiceType/>
                              <InvoiceDate>
                                <DateTime DateTimeQualifier="After">2017-02-01T00:00:00</DateTime>
                              </InvoiceDate>
                              <InvoiceTotals>
                                <TotalLineItems>1</TotalLineItems>
                                <InvoiceTotal>
                                  <MonetaryAmount>
                                    <MonetaryValue>13887.1700</MonetaryValue>
                                    <CurrencyCode>USD</CurrencyCode>
                                  </MonetaryAmount>
                                </InvoiceTotal>
                              </InvoiceTotals>
                            </orderRes:Invoice_Details>
                            <orderRes:Line_Items>
                              <orderRes:QTY>
                                <Measurement>
                                  <MeasurementValue>24.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">DR</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:QTY>
                              <orderRes:BO>
                                <Measurement>
                                  <MeasurementValue>24.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">DR</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:BO>
                              <orderRes:Size>
                                <Measurement>
                                  <MeasurementValue>55.0000</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">GL DR</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:Size>
                              <orderRes:item_number>783002</orderRes:item_number>
                              <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="LB">
                                <MonetaryAmount>
                                  <MonetaryValue>1.5540</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Unit_Price>
                              <orderRes:Line_total>
                                <MonetaryAmount>
                                 <MonetaryValue>13887.1700</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Line_total>
                              <orderRes:Product_Number Agency="AGIIS-ProductID">783002</orderRes:Product_Number>
                              <orderRes:Product_Description>ETHANOL 190 PRF PARASOLV A-1</orderRes:Product_Description>
                              <orderRes:SdsNumber>75493</orderRes:SdsNumber>
                              <orderRes:Lot_Number BatchNumberCreator="Manufacturer"/>
                              <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                              <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                              <orderRes:Vendor_Name>eastman</orderRes:Vendor_Name>
                           </orderRes:Line_Items>
                            <orderRes:Line_Items>
                              <orderRes:QTY>
                                <Measurement>
                                  <MeasurementValue>1.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:QTY>
                              <orderRes:BO>
                                <Measurement>
                                  <MeasurementValue></MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20"></UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:BO>
                              <orderRes:Size>
                                <Measurement>
                                  <MeasurementValue>1.0000</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:Size>
                              <orderRes:item_number>600973</orderRes:item_number>
                              <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="EA">
                                <MonetaryAmount>
                                  <MonetaryValue>0.0000</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Unit_Price>
                              <orderRes:Line_total>
                                <MonetaryAmount>
                                  <MonetaryValue>0.00</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Line_total>
                              <orderRes:Product_Number Agency="AGIIS-ProductID">600973</orderRes:Product_Number>
                              <orderRes:Product_Description>TRANSPORTATION SURCHG PK</orderRes:Product_Description>
                              <orderRes:Lot_Number BatchNumberCreator="Manufacturer"/>
                              <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                              <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                              <orderRes:Vendor_Name/>
                           </orderRes:Line_Items>
                           <orderRes:Line_Items>
                              <orderRes:QTY>
                                <Measurement>
                                  <MeasurementValue>1.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:QTY>
                              <orderRes:BO>
                                <Measurement>
                                  <MeasurementValue>0.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:BO>
                              <orderRes:Size>
                                <Measurement>
                                  <MeasurementValue>1.0000</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:Size>
                              <orderRes:item_number>644207</orderRes:item_number>
                              <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="EA">
                                <MonetaryAmount>
                                  <MonetaryValue>0.0000</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Unit_Price>
                              <orderRes:Line_total>
                                <MonetaryAmount>
                                  <MonetaryValue>0.00</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Line_total>
                              <orderRes:Product_Number Agency="AGIIS-ProductID">644207</orderRes:Product_Number>
                              <orderRes:Product_Description>UNV PKG DLVY CHG</orderRes:Product_Description>
                              <orderRes:Lot_Number BatchNumberCreator="Manufacturer"/>
                              <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                              <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                              <orderRes:Vendor_Name/>
                           </orderRes:Line_Items>
                        </orderRes:row> 
                        <orderRes:row>
                            <orderRes:Account_Manager/>
                            <orderRes:Customer_PO_Number>
                              <DocumentIdentifier>7400166276 REL:4249</DocumentIdentifier>
                            </orderRes:Customer_PO_Number>
                            <orderRes:Account_PO_Number/>
                            <orderRes:Univar_PO_Number/>
                            <orderRes:Order_Ship_Date>2016-02-19</orderRes:Order_Ship_Date>
                            <orderRes:Last_Modified_Date>2016-02-29T00:00:00</orderRes:Last_Modified_Date>
                            <orderRes:Sales_Office_ID>SP</orderRes:Sales_Office_ID>
                            <orderRes:Sales_Order_Number>
                              <DocumentReference>
                                <DocumentIdentifier>889355</DocumentIdentifier>
                              </DocumentReference>
                            </orderRes:Sales_Order_Number>
                            <orderRes:Order_Date>2016-02-17</orderRes:Order_Date>
                            <orderRes:CSR_Name>LEIGH HEDRICK</orderRes:CSR_Name>
                            <orderRes:CSR_Email>IELYD@UNIVARUSA.COM</orderRes:CSR_Email>
                            <orderRes:CSR_Phone></orderRes:CSR_Phone>
                            <orderRes:Status>L</orderRes:Status>
                            <orderRes:CURRENCY Domain="ISO-4217">USD</orderRes:CURRENCY>
                            <orderRes:Account>
                              <orderRes:Ship_To>
                                <PartnerInformation>
                                  <PartnerName>ROCHE CAROLINA INC</PartnerName>
                                  <PartnerIdentifier>001</PartnerIdentifier>
                                  <AddressInformation>
                                    <AddressLine>MANUFACTURING CHEMICALS</AddressLine>
                                    <CityName>FLORENCE</CityName>
                                    <StateOrProvince>SC</StateOrProvince>
                                    <PostalCode>29506</PostalCode>
                                    <PostalCountry></PostalCountry>
                                    <LocationCode></LocationCode>
                                  </AddressInformation>
                               </PartnerInformation>
                             </orderRes:Ship_To>
                             <orderRes:Bill_To>
                               <PartnerInformation>
                                  <PartnerName></PartnerName>
                                  <PartnerIdentifier>350428</PartnerIdentifier>
                                  <AddressInformation>
                                    <AddressLine>MANUFACTURING CHEMICALS</AddressLine>
                                    <CityName>FLORENCE</CityName>
                                    <StateOrProvince>SC</StateOrProvince>
                                    <PostalCode>29506</PostalCode>
                                    <PostalCountry></PostalCountry>
                                    <LocationCode></LocationCode>
                                  </AddressInformation>
                                </PartnerInformation>
                              </orderRes:Bill_To>
                              <orderRes:Corp_acct_id>0</orderRes:Corp_acct_id>
                            </orderRes:Account>
                            <orderRes:Invoice_Details>
                              <InvoiceNumber>
                                <DocumentReference>
                                <DocumentIdentifier>165738</DocumentIdentifier>
                                </DocumentReference>
                              </InvoiceNumber>
                              <InvoiceType/>
                              <InvoiceDate>
                                <DateTime DateTimeQualifier="After">2016-02-18T00:00:00</DateTime>
                              </InvoiceDate>
                              <InvoiceTotals>
                                <TotalLineItems>1</TotalLineItems>
                                <InvoiceTotal>
                                  <MonetaryAmount>
                                    <MonetaryValue>29619.6100</MonetaryValue>
                                    <CurrencyCode>USD</CurrencyCode>
                                  </MonetaryAmount>
                                </InvoiceTotal>
                              </InvoiceTotals>
                            </orderRes:Invoice_Details>
                            <orderRes:Line_Items>
                              <orderRes:QTY>
                                <Measurement>
                                  <MeasurementValue>45000.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">PO</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:QTY>
                              <orderRes:BO>
                                <Measurement>
                                  <MeasurementValue>45000.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">PO</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:BO>
                              <orderRes:Size>
                                <Measurement>
                                  <MeasurementValue>1.0000</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">LB</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:Size>
                              <orderRes:item_number>605649</orderRes:item_number>
                              <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="KG">
                                <MonetaryAmount>
                                  <MonetaryValue>1.4239</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Unit_Price>
                              <orderRes:Line_total>
                                <MonetaryAmount>
                                  <MonetaryValue>29616.3900</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Line_total>
                              <orderRes:Product_Number Agency="AGIIS-ProductID">605649</orderRes:Product_Number>
                              <orderRes:Product_Description>METHYLENE CHLORIDE</orderRes:Product_Description>
                              <orderRes:SdsNumber>OC79584</orderRes:SdsNumber>
                              <orderRes:Lot_Number BatchNumberCreator="Manufacturer">SP619297</orderRes:Lot_Number>
                              <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                              <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                              <orderRes:Vendor_Name>dow</orderRes:Vendor_Name>
                           </orderRes:Line_Items>
                            <orderRes:Line_Items>
                              <orderRes:QTY>
                                <Measurement>
                                  <MeasurementValue>1.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:QTY>
                              <orderRes:BO>
                                <Measurement>
                                  <MeasurementValue></MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20"></UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:BO>
                              <orderRes:Size>
                                <Measurement>
                                  <MeasurementValue>1.0000</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:Size>
                              <orderRes:item_number>644037</orderRes:item_number>
                              <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="EA">
                                <MonetaryAmount>
                                  <MonetaryValue>0.0000</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Unit_Price>
                              <orderRes:Line_total>
                                <MonetaryAmount>
                                  <MonetaryValue>0.00</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Line_total>
                              <orderRes:Product_Number Agency="AGIIS-ProductID">644037</orderRes:Product_Number>
                              <orderRes:Product_Description>UNV BULK DLVY CHG</orderRes:Product_Description>
                              <orderRes:Lot_Number BatchNumberCreator="Manufacturer"/>
                              <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                              <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                              <orderRes:Vendor_Name/>
                           </orderRes:Line_Items>
                           <orderRes:Line_Items>
                              <orderRes:QTY>
                                <Measurement>
                                  <MeasurementValue>1.00</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:QTY>
                              <orderRes:BO>
                                <Measurement>
                                  <MeasurementValue></MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20"></UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:BO>
                              <orderRes:Size>
                                <Measurement>
                                  <MeasurementValue>1.0000</MeasurementValue>
                                  <UnitOfMeasureCode Domain="UN-Rec-20">EA</UnitOfMeasureCode>
                                </Measurement>
                              </orderRes:Size>
                              <orderRes:item_number>777722</orderRes:item_number>
                              <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="EA">
                                <MonetaryAmount>
                                  <MonetaryValue>0.0000</MonetaryValue>
                                  <CurrencyCode Domain="ISO-4217">USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Unit_Price>
                              <orderRes:Line_total>
                                <MonetaryAmount>
                                  <MonetaryValue>0.00</MonetaryValue>
                                  <CurrencyCode>USD</CurrencyCode>
                                </MonetaryAmount>
                              </orderRes:Line_total>
                              <orderRes:Product_Number Agency="AGIIS-ProductID">777722</orderRes:Product_Number>
                              <orderRes:Product_Description>TRANSPORTATION SURCHG</orderRes:Product_Description>
                              <orderRes:Lot_Number BatchNumberCreator="Manufacturer"/>
                              <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                              <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                              <orderRes:Vendor_Name/>
                           </orderRes:Line_Items>
                        </orderRes:row> 
                      </orderRes:ResultSet>
                    </orderRes:OrderResponse>
                         
                    
  /orderdetails:
     displayName: Query using Customer Sales Order Number, Ship to Number and Shipped date range
     post:
      description: Query using Customer Purchase Order Number, Ship to Number and Shipped date range received from Salesforce
      body:
        application/xml:
          example: |
              <?xml version="1.0" encoding="UTF-8"?>
               <orderRes:OrderRequest xmlns="urn:cidx:names:specification:ces:schema:all:5:3" xmlns:types="http://com.univar/data/enterprise/core/types/1.1" xmlns:order="http://com.univar/data/enterprise/business/order/1.1" xmlns:orderRes="http://com.univar/data/enterprise/business/order/message/1.1">
               <order:Order_Date>
                           <types:FromDate>2015-06-07</types:FromDate>
                           <types:ToDate>2016-06-07</types:ToDate>
              </order:Order_Date>
              <order:Sales_Order_Number>
                <DocumentReference>
                  <DocumentIdentifier>370415</DocumentIdentifier>
                </DocumentReference>
              </order:Sales_Order_Number>
              <order:Sales_Office_ID>AT</order:Sales_Office_ID>              
              <order:Status>L</order:Status>
              <order:Account>
                           <order:Corp_acct_id Agency="AGIIS-EBID">4422</order:Corp_acct_id>
              </order:Account>
              </orderRes:OrderRequest>
           
      responses:  
        200:
          body:
            application/xml:
              example: |
                      <?xml version="1.0" encoding='windows-1252'?>
                      <orderRes:OrderResponse xmlns:orderRes="http://com.univar/data/enterprise/business/order/message/1.0">
                      <orderRes:ResultSet>
                        <orderRes:row xmlns:orderRes="http://com.univar/data/enterprise/business/order/message/1.0">
                        <orderRes:Account_Manager/>
                        <orderRes:Customer_PO_Number>
                          <DocumentIdentifier>R45388</DocumentIdentifier>
                        </orderRes:Customer_PO_Number>
                        <orderRes:Account_PO_Number>
                          <DocumentIdentifier/>
                        </orderRes:Account_PO_Number>
                        <orderRes:Univar_PO_Number>
                          <DocumentIdentifier/>
                        </orderRes:Univar_PO_Number>
                        <orderRes:Product_Name/>
                        <orderRes:Lot_Number BatchNumberCreator="Manufacturer"/>
                        <orderRes:Order_Ship_Date>2016-02-05</orderRes:Order_Ship_Date>
                        <orderRes:Invoice_Number>
                          <DocumentReference>
                            <DocumentIdentifier>280853</DocumentIdentifier>
                          </DocumentReference>
                        </orderRes:Invoice_Number>
                        <orderRes:Sales_Office_ID>KT</orderRes:Sales_Office_ID>
                        <orderRes:Sales_Order_Number>
                          <DocumentReference>
                            <DocumentIdentifier>55342</DocumentIdentifier>
                          </DocumentReference>
                        </orderRes:Sales_Order_Number>
                        <orderRes:Ship_from_Warehouse>
                          <PartnerInformation>
                            <PartnerName/>
                            <PartnerIdentifier Agency="AGIIS-EBID"/>
                          </PartnerInformation>
                        </orderRes:Ship_from_Warehouse>
                        <orderRes:Requesting_Warehouse>
                        <RequestedDocumentTypeCode Domain="UN/EDIFACT 1001"/>
                        <DocumentRecipientInformation DeliveryMethodQualifier="Email">
                        <DocumentRecipientPartner PartnerRole="AdditionalCarrier">
                        <PartnerInformation>
                          <PartnerName/>
                          <PartnerIdentifier Agency="AGIIS-EBID"/>
                        </PartnerInformation>
                        </DocumentRecipientPartner>
                        <DocumentDeliveryMethod/>
                        <LanguageCode Domain="ISO-639-2T"/>
                        <NumberOfOriginals/>
                        <NumberOfCopies/>
                        </DocumentRecipientInformation>
                        </orderRes:Requesting_Warehouse>
                        <orderRes:Shipping_Type/>
                        <orderRes:Shipping_Term Domain="ANSI-ASC-X12-146"/>
                        <orderRes:Product_Customer_code Agency="AGIIS-ProductID"/>
                        <orderRes:Univar_Product_code Agency="AGIIS-ProductID"/>
                        <orderRes:Vendor_Name/>
                        <orderRes:Quantity_Shipped_Customer>
                          <Measurement>
                            <MeasurementValue/>
                            <UnitOfMeasureCode Domain="UN-Rec-20"/>
                          </Measurement>
                        </orderRes:Quantity_Shipped_Customer>
                        <orderRes:Shipping_Method/>
                        <orderRes:Vendor_Shipment_Method/>
                        <orderRes:Quantity_Shipped_From_Vendor>
                          <Measurement>
                            <MeasurementValue/>
                            <UnitOfMeasureCode Domain="UN-Rec-20"/>
                          </Measurement>
                        </orderRes:Quantity_Shipped_From_Vendor>
                        <orderRes:Product_Number Agency="AGIIS-ProductID"/>
                        <orderRes:Order_Date>2015-12-08</orderRes:Order_Date>
                        <orderRes:Status>CLOSED</orderRes:Status>
                        <orderRes:Ship_to_name>
                        <PartnerInformation>
                          <PartnerName/>
                          <PartnerIdentifier Agency="AGIIS-EBID"/>
                          <AddressInformation>
                            <AddressLine/>
                            <CityName/>
                            <StateOrProvince/>
                            <PostalCode/>
                            <PostalCountry/>
                            <LocationCode Domain="AGIIS-EBID"/>
                            </AddressInformation>
                            </PartnerInformation>
                            </orderRes:Ship_to_name>
                            <orderRes:ESTIMATED_SHIP_DATE>
                            <DateTime DateTimeQualifier="After"/>
                            </orderRes:ESTIMATED_SHIP_DATE>
                            <orderRes:ESTIMATED_DELIVERY_DATE/>
                            <orderRes:FOB/>
                            <orderRes:SHIP_VIA>
                              <PartnerInformation>
                                <PartnerName/>
                                <PartnerIdentifier Agency="AGIIS-EBID"/>
                              <AddressInformation>
                               <AddressLine/>
                               <CityName/>
                               <StateOrProvince/>
                               <PostalCode/>
                               <PostalCountry/>
                               <LocationCode Domain="ISO-3166-1"/>
                              </AddressInformation>
                              </PartnerInformation>
                             </orderRes:SHIP_VIA>
                             <orderRes:CURRENCY Domain="ISO-4217"/>
                             <orderRes:QTY>
                              <Measurement>
                              <MeasurementValue/>
                              <UnitOfMeasureCode Domain="UN-Rec-20"/>
                              </Measurement>
                            </orderRes:QTY>
                            <orderRes:BO>
                            <Measurement>
                              <MeasurementValue/>
                              <UnitOfMeasureCode Domain="UN-Rec-20"/>
                            </Measurement>
                            </orderRes:BO>
                            <orderRes:Size>
                            <Measurement>
                              <MeasurementValue/>
                              <UnitOfMeasureCode Domain="UN-Rec-20"/>
                            </Measurement>
                            </orderRes:Size>
                            <orderRes:item_number/>
                            <orderRes:Product_Description/>
                            <orderRes:Unit_Price GlobalMaterialUnitOfMeasureCode="a">
                            <MonetaryAmount>
                              <MonetaryValue/>
                              <CurrencyCode Domain="ISO-4217"/>
                            </MonetaryAmount>
                            </orderRes:Unit_Price>
                            <orderRes:Line_total>
                              <MonetaryAmount>
                                <MonetaryValue/>
                                <CurrencyCode Domain="ISO-4217"/>
                              </MonetaryAmount>
                            </orderRes:Line_total>
                            <orderRes:Last_Modified_Date>2016-02-29</orderRes:Last_Modified_Date>
                            <orderRes:Account>
                              <orderRes:Ship_To Agency="AGIIS-EBID"/>
                              <orderRes:Bill_To Agency="AGIIS-EBID"/>
                              <orderRes:Corp_acct_id Agency="AGIIS-EBID"/>
                            </orderRes:Account>
                          </orderRes:row>  
                         </orderRes:ResultSet>
                        </orderRes:OrderResponse> 
                           
/cases-orderdetails:
   displayName: Query using Customer Sales Order Number, Ship to Number and Shipped date range
   post:
    description: Query using Customer Purchase Order Number, Ship to Number and Shipped date range received from Salesforce
    body:
      application/xml:
        example: |
          <CaseSearchRequest>
            <Lot_Number></Lot_Number>
            <ShipTo_Number>161267</ShipTo_Number>
            <Shipped_Date_Range>20150102</Shipped_Date_Range>
            <Invoice_Number>26910</Invoice_Number>
            <Sales_Office_Code>CL</Sales_Office_Code>
            <Product_Number>192220</Product_Number>
            <ShipTo_Number>160053</ShipTo_Number>
            <Shipped_Date_Range>20150729</Shipped_Date_Range>
            <Sales_Order_Number>760501</Sales_Order_Number>
            <Sales_Office_Code>IN</Sales_Office_Code>
            <Customer_PO>MU637359</Customer_PO>
            <ShipTo_Number>697908</ShipTo_Number>
            <Shipped_Date_Range>20150102</Shipped_Date_Range>
          </CaseSearchRequest
    responses:  
      200:
        body:
          application/xml:
            example: |
                    <response>
                      <record>
                        <Customer_Ship_To_Number>362688</Customer_Ship_To_Number>
                        <Customer_Ship_To_Name>292416</Customer_Ship_To_Name>
                        <Sales_Order_Number>787725</Sales_Order_Number>
                        <Invoice_Number>119564</Invoice_Number>
                        <Sales_Office_ID>MV</Sales_Office_ID>
                        <Customer_PO_Number>M001025-446</Customer_PO_Number>
                        <Order_Ship_Date>20151013</Order_Ship_Date>
                        <Invoice_Number_Sales_Office>119564MV</Invoice_Number_Sales_Office_Unique_ID>
                      </record>
                    </response>
/invoices:
   displayName: Query using Customer Sales Order Number, Ship to Number and Shipped date range
   post:
    description: Query using Customer Purchase Order Number, Ship to Number and Shipped date range received from Salesforce
    body:
      application/xml:
        example: |
          <?xml version="1.0" encoding="UTF-8"?>
            <invoiceReqRes:InvoiceRequest xmlns="urn:cidx:names:specification:ces:schema:all:5:3" xmlns:typ="http://com.univar/data/enterprise/core/types/1.1" xmlns:order="http://com.univar/data/enterprise/business/order/1.1" xmlns:invoice="http://com.univar/data/enterprise/business/invoice/1.0" xmlns:invoiceReqRes="http://com.univar/data/enterprise/business/invoice/message/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <order:Status>N</order:Status>
            <order:Source>USA_DCS</order:Source>
            <order:Account>
              <order:Corp_acct_id Agency="AGIIS-EBID">4422</order:Corp_acct_id>
            </order:Account>
            <invoice:Invoice_Date>
              <typ:FromDate>2015-06-07</typ:FromDate>
              <typ:ToDate>2016-06-07</typ:ToDate>
            </invoice:Invoice_Date>
          </invoiceReqRes:InvoiceRequest>
    responses:  
      200:
        body:
          application/xml:
            example: |
                    <InvoiceResponse>
                      <ResultSet>
                        <row>
                          <Invoice_Number>
                            <DocumentReference>
                              <DocumentIdentifier>379530</DocumentIdentifier>
                            </DocumentReference>
                          </Invoice_Number>
                          <Invoice_Date>2016-01-18T00:00:00</Invoice_Date>
                          <Customer_PO_Number>
                            <DocumentIdentifier/>
                          </Customer_PO_Number>
                          <Sales_Order_Number>
                            <DocumentReference>
                              <DocumentIdentifier>493279</DocumentIdentifier>
                            </DocumentReference>
                          </Sales_Order_Number>
                          <Order_Date>1900-01-01T00:00:00</Order_Date>
                          <Status xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
                          <Payment_Date/>
                          <Total_Invoice_Amount>0.00</Total_Invoice_Amount>
                          <Total_Paid_Amount/>
                          <Currency xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
                          <Order_Shipment_Date>2016-01-18T00:00:00</Order_Shipment_Date>
                          <Sales_Office_ID>OD</Sales_Office_ID>
                          <Account>
                            <Ship_To>
                              <PartnerInformation>
                                <PartnerName/>
                                <PartnerIdentifier>001</PartnerIdentifier>
                              <AddressInformation>
                                 <AddressLine/>
                                 <CityName/>
                                 <StateOrProvince/>
                                 <PostalCode/>
                                 <PostalCountry/>
                                 <LocationCode/>
                                 </AddressInformation>
                            </PartnerInformation>
                          </Ship_To>
                          <Bill_To>
                            <PartnerInformation>
                              <PartnerName/>
                              <PartnerIdentifier>703275</PartnerIdentifier>
                              <AddressInformation>
                               <AddressLine/>
                               <CityName/>
                               <StateOrProvince/>
                               <PostalCode/>
                               <PostalCountry/>
                               <LocationCode/>
                              </AddressInformation>
                            </PartnerInformation>
                          </Bill_To>
                          <Corp_acct_id/>
                        </Account>
                      </row>
                      </ResultSet>
                    </InvoiceResponse>          

/order:
  post:
    description: get purchase order for terminex
    body:
      application/xml:
        example: |
         s
    responses:
      200:
        body:
          application/xml:
            example: |                    
              asas                 